{
 "title": "Theodolite - Stream Processing and Scaling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (pod) (irate(container_cpu_usage_seconds_total{pod=~\"shuffle-kstreams.*\"}[30s])) * 100"
    }
   ]
  },
  {
   "title": "HPA CPU Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg by (pod) (irate(container_cpu_usage_seconds_total{pod=~\"shuffle-kstreams.*\"}[30s])) * 100) without (pod)"
    }
   ]
  },
  {
   "title": "Throughput 10s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumergroup,topic) (rate(kafka_consumergroup_current_offset{topic='input'}[10s]) >= 0)"
    }
   ]
  },
  {
   "title": "Detailed Input Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_current_offset{topic='input'}[10s])"
    }
   ]
  },
  {
   "title": "Record Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (kafka_consumergroup_lag >= 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "HPA Input Lag Metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_lag{topic=\"input\"}[20s])) by (consumergroup)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_brokertopicmetrics_messagesin_total{topic='input'}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRegisteredTaskManagers) by (job)",
     "legendFormat": "{{job}} (Flink)"
    },
    {
     "expr": "count(com_hazelcast_metrics_activemembers) by(job)",
     "legendFormat": "{{job}} (Hazelcast Jet)"
    },
    {
     "expr": "count(kafka_streams_stream_thread_metrics_process_records_avg) by (job)",
     "legendFormat": "{{job}} (Kafka Streams)"
    },
    {
     "expr": "count({__name__=~\"org_apache_samza_container_samzacontainermetrics_samza_container_.*_count\", name=\"process-envelopes\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(consumergroup,topic) (kafka_consumergroup_current_offset{topic='input'} >= 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Out Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_brokertopicmetrics_messagesin_total{topic='output'}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records Produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partition_current_offset)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Dropped Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(com_hazelcast_jet_metrics_lateeventsdropped[30s])) by(job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_streams_stream_task_metrics_dropped_records_total[30s])) by (job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_numLateRecordsDropped[30s])) by(job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_org_apache_beam_runners_core_LateDataDroppingDoFnRunner_droppedDueToLateness[30s])) by (job) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "kafka_topic_partitions", "legendFormat": "{{topic}}" }
   ]
  }
 ]
}