kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

