apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: shufflebench-kstreams-baseline-atp
spec:
  benchmark: shuffle-kstreams
  load:
    loadType: "MessagesPerSecond"
    loadValues: [80000] # reduce - 50000 # original 250000
  resources:
    resourceType: "Instances"
    resourceValues: [1] # reduce # original 9
  slos:
    - name: throughput
      properties: {}
  execution:
    metric: capacity
    strategy:
      name: "LinearSearch"
    duration: 900 # in seconds # original 900
    loadGenerationDelay: 30 # in seconds # original 30
    repetitions: 1 # 1 should be enough # original 3
  configOverrides:
    - patcher:
        type: "EnvVarPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          container: "shuffle-kstreams"
          variableName: "MATCHER_ZIPF_NUM_RULES"
      value: "10000" # less, maybe 100000 # original 1000000
      # autoscaling config might be needed here
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-kstreams-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra" # original "sut"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-load-generator-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
    - patcher:
        type: "NodeSelectorPatcher"
        resource: "shuffle-latency-exporter-deployment.yaml"
        properties:
          variableName: "type"
      value: "infra"
